# Generated by Django 5.1.1 on 2025-08-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
