# Generated by Django 5.2.4 on 2025-07-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
