# Generated by Django 5.2.4 on 2025-07-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.DeleteModel(
            name='conversation',
        ),
        migrations.DeleteModel(
            name='message',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
