# Generated by Django 5.2.4 on 2025-07-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participants_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='chats.message'),
        ),
    ]
