# Generated by Django 5.1.1 on 2025-07-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0019_alter_conversation_participants_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
