# Generated by Django 5.2.4 on 2025-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0028_alter_conversation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='participants_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants_id',
            field=models.ManyToManyField(null=True, related_name='participants_id', to='chats.user'),
        ),
    ]
