#!/bin/bash

echo "Starting Kubernetes cluster with minikube..."
minikube start

echo "Verifying cluster status..."
kubectl cluster-info

echo "Listing all pods in all namespaces..."
kubectl get pods --all-namespaces