# Generated by Django 5.1.1 on 2025-07-19 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0018_alter_message_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participants_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='chats.message'),
        ),
    ]
