# Generated by Django 5.2.4 on 2025-07-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0027_remove_message_participant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chats.user'),
        ),
    ]
