# Generated by Django 5.2.4 on 2025-07-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
