# Generated by Django 5.2.4 on 2025-07-19 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_body', models.CharField(max_length=255)),
                ('sent_at', models.DateField(auto_now=True)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chats.user')),
            ],
        ),
    ]
