# Generated by Django 5.2.4 on 2025-07-19 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('participants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='chats.user')),
            ],
        ),
    ]
