# Generated by Django 5.2.4 on 2025-07-19 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_alter_message_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chats.user'),
        ),
    ]
