# Generated by Django 5.1.1 on 2025-07-26 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0022_remove_conversation_participants_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participants_id',
            field=models.ManyToManyField(blank=True, null=True, to='chats.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chats.user'),
        ),
    ]
