# Generated by Django 5.1.1 on 2025-07-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0023_alter_conversation_participants_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chats.user'),
        ),
    ]
