# Generated by Django 5.2.4 on 2025-07-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0024_conversation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
