# Generated by Django 5.2.4 on 2025-07-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0026_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='participant_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants_id', to='chats.user'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chats.user'),
        ),
    ]
